# Generated by Django 4.0.3 on 2022-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Заказ в обработке'), ('completed', 'Заказ выполнен')], default='in_progress', max_length=100, verbose_name='Статус заказ'),
        ),
    ]
