# Generated by Django 4.0.3 on 2022-06-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
    ]
