# Generated by Django 4.0.3 on 2022-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_review_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
